export const MISSIONS=[
 {id:'ashes',title:'Run through the ashes',place:'Jamestown',year:'1676',mode:'stealth',genre:'STEALTH / ESCAPE',role:'A civilian caught in the rebellion.',brief:'The town is burning. Slip past the patrols and reach the river.',objective:'Reach the river. Avoid the patrols.',art:'frontier',after:'Bacon’s Rebellion frightened Virginia’s elite. Its aftermath helped harden racial divisions and accelerate the shift toward enslaved African labor.',lines:[[1,'NEIGHBOR','Bacon’s men burned Jamestown. The river is our way out.'],[14,'FUGITIVE','Black and white laborers fought together. The planters won’t forget that.']],points:[[-10,4,'Cross the square'],[10,-7,'Reach the storehouse'],[0,-23,'Escape to the river']],pointLines:['Keep low. Their lanterns give the patrols away.','They fear another united revolt. Tighter racial control is coming.','You made it. Others will live with the consequences.'],start:[0,24],enemies:[[-9,9],[9,5],[-5,-5],[13,-15]],seed:4},
 {id:'haven',title:'A place for everyone',place:'Pennsylvania',year:'1682',mode:'builder',genre:'TOWN BUILDER',role:'An organizer in Penn’s new colony.',brief:'Boats keep arriving. Build homes and farms. Give twelve newcomers a place to live.',objective:'Shelter 12 newcomers. Build 2 farms and a meetinghouse.',art:'harbor',after:'William Penn’s proprietary colony welcomed Quakers and other migrants. Pennsylvania had no established official church.',lines:[[2,'PENN','The charter is ours. Let’s give these families a place to begin.'],[16,'NEWCOMER','A Quaker, a Baptist, an Anglican. There’s a place here for each of us.'],[35,'FRIEND','No official church. No seats reserved for inherited rank.']]},
 {id:'crown',title:'Break the king’s seal',place:'Boston',year:'1689 → 1690',mode:'stealth',genre:'STEALTH / COURIER',role:'A messenger after the overthrow of Andros.',brief:'Royal loyalists patrol the docks. Get news of the Bill of Rights to the harbor.',objective:'Carry the dispatch past the guards.',art:'harbor',after:'The English Bill of Rights limited the crown and strengthened Parliament. Hobbes emphasized sovereign power for security; Locke emphasized consent and protected rights.',lines:[[1,'PRINTER','London’s Bill of Rights has arrived. William and Mary must answer to Parliament.'],[16,'WATCHMAN','Andros is gone. The Dominion has collapsed. Don’t let the loyalists catch you.']],points:[[11,9,'Reach the press'],[-10,-6,'Cross Parliament Lane'],[0,-23,'Deliver the Bill of Rights']],pointLines:['The Bill of Rights: Parliament checks the crown’s power.','Hobbes trusts a strong sovereign to keep order. Locke says rulers must protect rights.','Life, liberty, property. Consent gives government its authority.'],start:[0,24],enemies:[[8,3],[-10,2],[5,-10],[-9,-18]],seed:8},
 {id:'molasses',title:'Run the blockade',place:'Atlantic coast',year:'1733',mode:'naval',genre:'NAVAL COMBAT',role:'Captain of a colonial trading ship.',brief:'Pick up five cargo barrels and make the northern harbor. Dodge cannon fire. Return your own.',objective:'Collect 5 cargo barrels. Reach the north harbor.',art:'harbor',after:'The Molasses Act taxed foreign molasses. Salutary neglect meant weak enforcement, so smuggling flourished even though it remained illegal.',lines:[[1,'MATE','French molasses is cheaper. London puts a duty on it.'],[14,'MATE','Walpole’s men hardly check. They call it salutary neglect.'],[35,'LOOKOUT','Patrol off the bow! Loose enforcement doesn’t make this legal.']]},
 {id:'pitt',title:'Hold until the money comes',place:'The Ohio frontier',year:'1754 → 1758',mode:'defense',genre:'TACTICAL DEFENSE',role:'A colonial officer with too few supplies.',brief:'Place defenders. Hold three approaches. Help is coming—but not from the Albany Plan.',objective:'Hold the fort through the assault.',art:'frontier',after:'The Albany Plan proposed colonial union but was never implemented. Pitt’s major investment in troops and supplies helped turn the war in Britain’s favor from 1758.',lines:[[1,'RUNNER','Albany’s union plan failed. The colonies won’t give up their authority.'],[13,'OFFICER','Franklin wanted joint defense under the crown. We’re still on our own.'],[26,'RUNNER','Pitt’s funding has arrived! Guns, supplies, reinforcements—use them!']]},
 {id:'quebec',title:'Take the heights',place:'Outside Quebec',year:'1759',mode:'fps',genre:'FIRST-PERSON BATTLE',role:'A British infantry scout.',brief:'Push through the French positions. Clear each objective and capture the ridge.',objective:'Take 3 positions on the road to Quebec.',art:'frontier',after:'Quebec fell in 1759 after Wolfe defeated Montcalm. Both commanders were fatally wounded. Montreal fell in 1760; the Treaty of Paris ended the war in 1763.',lines:[[1,'OFFICER','Pitt paid for this push. Keep moving. Use the cover.'],[19,'SCOUT','Wolfe’s advancing on the heights. Clear a route through.']],points:[[-10,6,'Silence the forward battery'],[10,-8,'Clear the outer defenses'],[0,-23,'Capture the ridge']],pointLines:['Forward battery secured. Push through!','The heights are ours. Wolfe and Montcalm both fell in the battle.','Quebec falls. Montreal follows in 1760. The war ends in 1763.'],start:[0,24],enemies:[[-11,10],[-5,4],[7,5],[12,-5],[-11,-8],[2,-11],[10,-19],[-7,-21]],seed:12},
 {id:'debt',title:'Someone has to pay',place:'British North America',year:'1763',mode:'crisis',genre:'CRISIS MANAGEMENT',role:'An official staring at the cost of victory.',brief:'Keep Canada, the Ohio frontier, and Florida supplied for sixty seconds. Your treasury is nearly empty.',objective:'Keep the empire supplied for 60 seconds.',art:'printshop',after:'Britain’s victory created debt and new defense costs. Taxes, tighter control, and frontier disputes would strain ties with colonists accustomed to autonomy.',lines:[[1,'TREASURER','Canada and Florida are ours. So is the bill.'],[15,'COLONIST','We celebrated as British subjects. Now you demand more money?'],[34,'RUNNER','Native nations still defend this land. A treaty doesn’t erase them.'],[48,'COLONIST','We governed ourselves for years. Why the tighter control now?']]}
];
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function blocked(x,z,walls,radius=.5){return Math.abs(x)>23.7||Math.abs(z)>28.5||walls.some(w=>Math.abs(x-w.x)<w.w/2+radius&&Math.abs(z-w.z)<w.d/2+radius);}
export function slideMove(entity,dx,dz,walls,radius=.5){if(!blocked(entity.x+dx,entity.z,walls,radius))entity.x+=dx;if(!blocked(entity.x,entity.z+dz,walls,radius))entity.z+=dz;}
export function clearLine(a,b,walls){const dist=distance(a,b),steps=Math.ceil(dist/.65);for(let i=1;i<steps;i++){const k=i/steps;if(walls.some(w=>Math.abs(a.x+(b.x-a.x)*k-w.x)<w.w/2&&Math.abs(a.z+(b.z-a.z)*k-w.z)<w.d/2))return false;}return true;}
export function makeWalls(seed=1){
 const walls=[{x:-20,z:13,w:7,d:8,h:5},{x:20,z:15,w:7,d:8,h:4},{x:-19,z:-8,w:8,d:9,h:6},{x:20,z:-9,w:6,d:8,h:5},{x:0,z:15,w:4,d:2,h:1.7},{x:-7,z:0,w:6,d:2,h:1.8},{x:6,z:-1,w:2,d:8,h:2},{x:0,z:-15,w:7,d:2,h:1.8},{x:16,z:-22,w:3,d:3,h:2},{x:-15,z:22,w:3,d:3,h:2}];
 if(seed===8)walls.push({x:-2,z:5,w:2,d:6,h:3});return walls;
}
export function newFPS(mission,difficulty='normal'){
 return {player:{x:mission.start[0],z:mission.start[1],yaw:0,pitch:0,hp:100,jump:0,vy:0},walls:makeWalls(mission.seed),enemies:mission.enemies.map(([x,z],i)=>({x,z,sx:x,sz:z,hp:mission.mode==='fps'?2:3,alert:0,cool:2+i*.2,phase:i*2,angle:0,dead:0})),point:0,capture:0,time:0,lastDamage:-20,noise:0,noiseAt:{x:0,z:0},round:1,reload:0,shot:0,hurt:0,kills:0,shots:0,done:false,failed:false,difficulty};
}
export function updateFPS(s,mission,input,dt){
 if(s.done||s.failed)return;dt=Math.min(dt,.05);s.time+=dt;s.shot=Math.max(0,s.shot-dt);s.hurt=Math.max(0,s.hurt-dt);s.noise=Math.max(0,s.noise-dt);
 const p=s.player;const sprint=input.sprint?1.55:1,crouch=input.crouch?.58:1;let f=(input.forward||0)-(input.back||0),r=(input.right||0)-(input.left||0);const len=Math.hypot(f,r)||1;
 p.yaw+=(input.turn||0)*dt*1.9;const speed=5.1*sprint*crouch;slideMove(p,(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*r)/len*speed*dt,(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*r)/len*speed*dt,s.walls);
 if(p.jump>0||p.vy>0){p.vy-=15*dt;p.jump=Math.max(0,p.jump+p.vy*dt);if(p.jump===0)p.vy=0;}
 if(s.reload>0){s.reload-=dt;if(s.reload<=0)s.round=1;}
 if(s.round===0&&s.reload<=0)s.reload=1.35;
 for(const e of s.enemies){if(e.hp<=0){e.dead+=dt;continue;}e.cool-=dt;const d=distance(p,e),los=d<25&&clearLine(p,e,s.walls);let spotted=false;
  if(mission.mode==='fps')spotted=los&&d<24;
  else {const forward=Math.atan2(-(p.x-e.x),-(p.z-e.z));const facing=Math.atan2(Math.sin(forward-e.angle),Math.cos(forward-e.angle));spotted=los&&(d<3.1||Math.abs(facing)<.76&&d<(input.crouch?7:input.sprint?15:11));}
  e.alert=clamp(e.alert+(spotted?dt*1.8:-dt*.45),0,1);
  let target;if(e.alert>.45)target=p;else if(s.noise>0&&distance(e,s.noiseAt)<19)target=s.noiseAt;else target={x:e.sx+Math.sin(s.time*.36+e.phase)*4,z:e.sz+Math.cos(s.time*.36+e.phase)*4};
  const td=distance(e,target);if(td>1.5&&(e.alert<.8||d>7)){const mx=(target.x-e.x)/td,mz=(target.z-e.z)/td;slideMove(e,mx*dt*(e.alert>.5?2.1:1.2),mz*dt*(e.alert>.5?2.1:1.2),s.walls,.4);e.angle=Math.atan2(-mx,-mz);}
  if(e.alert>.82&&los&&e.cool<=0){const damage=s.difficulty==='story'?4:8;p.hp-=damage;s.lastDamage=s.time;s.hurt=.32;e.cool=mission.mode==='fps'?1.8:2.3;}
 }
 if(s.time-s.lastDamage>5)p.hp=Math.min(100,p.hp+dt*9);
 const goal=mission.points[s.point];if(goal){const near=Math.hypot(p.x-goal[0],p.z-goal[1])<3.4;const contested=mission.mode==='fps'&&s.enemies.some(e=>e.hp>0&&Math.hypot(e.x-goal[0],e.z-goal[1])<8);s.capture=near&&!contested?s.capture+dt:Math.max(0,s.capture-dt*2);if(s.capture>1.1){s.point++;s.capture=0;if(s.point===mission.points.length)s.done=true;}}
 if(p.hp<=0){p.hp=0;s.failed=true;}
}
export function fireFPS(s,mission){
 if(s.done||s.failed)return false;
 if(mission.mode==='stealth'){if(s.noise>0)return false;s.noise=4;s.noiseAt={x:s.player.x-Math.sin(s.player.yaw)*9,z:s.player.z-Math.cos(s.player.yaw)*9};s.shot=.2;return true;}
 if(!s.round||s.reload>0)return false;s.round=0;s.reload=1.35;s.shot=.23;s.shots++;
 const p=s.player;let selected=null,closest=40;
 for(const e of s.enemies){if(e.hp<=0)continue;const d=distance(p,e),a=Math.atan2(-(e.x-p.x),-(e.z-p.z));const diff=Math.abs(Math.atan2(Math.sin(a-p.yaw),Math.cos(a-p.yaw)));const aim=Math.atan2(.15,d);if(diff<Math.max(.04,.62/d)&&Math.abs(p.pitch-aim)<.16&&d<closest&&clearLine(p,e,s.walls)){closest=d;selected=e;}}
 if(selected){selected.hp-=1;selected.alert=1;if(selected.hp<=0)s.kills++;return 'hit';}return true;
}
