// Prerecorded synthetic performances; generated locally with Kokoro-82M.
export const VOICE_LINES = [
  {
    "id": "ashes.brief",
    "speaker": "NARRATOR",
    "text": "The town is burning. Slip past the patrols and reach the river.",
    "group": "ashes",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-ashes-brief-0d13d606d.mp3",
    "duration": 4.134,
    "peak": 0.86,
    "rms": 0.149
  },
  {
    "id": "ashes.after",
    "speaker": "NARRATOR",
    "text": "Bacon’s Rebellion frightened Virginia’s elite. Its aftermath helped harden racial divisions and accelerate the shift toward enslaved African labor.",
    "group": "ashes",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-ashes-after-ee50447b3.mp3",
    "duration": 10.353,
    "peak": 0.8352,
    "rms": 0.15
  },
  {
    "id": "ashes.line0",
    "speaker": "NEIGHBOR",
    "text": "Bacon’s men burned Jamestown. The river is our way out.",
    "group": "ashes",
    "voice": "af_heart",
    "speed": 1.08,
    "lang": "en-us",
    "file": "voice-ashes-line0-3f1ed0c74.mp3",
    "duration": 3.344,
    "peak": 0.86,
    "rms": 0.1314
  },
  {
    "id": "ashes.line1",
    "speaker": "FUGITIVE",
    "text": "Black and white laborers fought together. The planters won’t forget that.",
    "group": "ashes",
    "voice": "am_fenrir",
    "speed": 1.01,
    "lang": "en-us",
    "file": "voice-ashes-line1-fe2ddf673.mp3",
    "duration": 3.879,
    "peak": 0.86,
    "rms": 0.0965
  },
  {
    "id": "ashes.point0",
    "speaker": "DISPATCH",
    "text": "Keep low. Their lanterns give the patrols away.",
    "group": "ashes",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-ashes-point0-3ba175dd0.mp3",
    "duration": 2.829,
    "peak": 0.7581,
    "rms": 0.15
  },
  {
    "id": "ashes.point1",
    "speaker": "DISPATCH",
    "text": "They fear another united revolt. Tighter racial control is coming.",
    "group": "ashes",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-ashes-point1-ca90cceff.mp3",
    "duration": 4.106,
    "peak": 0.86,
    "rms": 0.1363
  },
  {
    "id": "ashes.point2",
    "speaker": "DISPATCH",
    "text": "You made it. Others will live with the consequences.",
    "group": "ashes",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-ashes-point2-d42df82bb.mp3",
    "duration": 2.957,
    "peak": 0.8478,
    "rms": 0.15
  },
  {
    "id": "haven.brief",
    "speaker": "NARRATOR",
    "text": "Boats keep arriving. Build homes and farms. Give twelve newcomers a place to live.",
    "group": "haven",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-haven-brief-b7c426fb5.mp3",
    "duration": 5.567,
    "peak": 0.86,
    "rms": 0.1435
  },
  {
    "id": "haven.after",
    "speaker": "NARRATOR",
    "text": "William Penn’s proprietary colony welcomed Quakers and other migrants. Pennsylvania had no established official church.",
    "group": "haven",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-haven-after-25cbea82c.mp3",
    "duration": 8.302,
    "peak": 0.86,
    "rms": 0.1499
  },
  {
    "id": "haven.line0",
    "speaker": "PENN",
    "text": "The charter is ours. Let’s give these families a place to begin.",
    "group": "haven",
    "voice": "bm_fable",
    "speed": 0.97,
    "lang": "en-gb",
    "file": "voice-haven-line0-1bee20ea1.mp3",
    "duration": 4.525,
    "peak": 0.86,
    "rms": 0.1136
  },
  {
    "id": "haven.line1",
    "speaker": "NEWCOMER",
    "text": "A Quaker, a Baptist, an Anglican. There’s a place here for each of us.",
    "group": "haven",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "voice-haven-line1-3ce004a0a.mp3",
    "duration": 4.229,
    "peak": 0.86,
    "rms": 0.1158
  },
  {
    "id": "haven.line2",
    "speaker": "FRIEND",
    "text": "No official church. No seats reserved for inherited rank.",
    "group": "haven",
    "voice": "bf_emma",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-haven-line2-b6512d7be.mp3",
    "duration": 3.75,
    "peak": 0.86,
    "rms": 0.1394
  },
  {
    "id": "crown.brief",
    "speaker": "NARRATOR",
    "text": "Royal loyalists patrol the docks. Get news of the Bill of Rights to the harbor.",
    "group": "crown",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-crown-brief-946e66fa6.mp3",
    "duration": 5.385,
    "peak": 0.7155,
    "rms": 0.15
  },
  {
    "id": "crown.after",
    "speaker": "NARRATOR",
    "text": "The English Bill of Rights limited the crown and strengthened Parliament. Hobbes emphasized sovereign power for security; Locke emphasized consent and protected rights.",
    "group": "crown",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-crown-after-d9164cd1a.mp3",
    "duration": 11.139,
    "peak": 0.7976,
    "rms": 0.15
  },
  {
    "id": "crown.line0",
    "speaker": "PRINTER",
    "text": "London’s Bill of Rights has arrived. William and Mary must answer to Parliament.",
    "group": "crown",
    "voice": "bm_george",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-crown-line0-1990180d4.mp3",
    "duration": 5.289,
    "peak": 0.7508,
    "rms": 0.15
  },
  {
    "id": "crown.line1",
    "speaker": "WATCHMAN",
    "text": "Andros is gone. The Dominion has collapsed. Don’t let the loyalists catch you.",
    "group": "crown",
    "voice": "am_michael",
    "speed": 1.06,
    "lang": "en-us",
    "file": "voice-crown-line1-574938abd.mp3",
    "duration": 5.135,
    "peak": 0.86,
    "rms": 0.1068
  },
  {
    "id": "crown.point0",
    "speaker": "DISPATCH",
    "text": "The Bill of Rights: Parliament checks the crown’s power.",
    "group": "crown",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-crown-point0-07d332582.mp3",
    "duration": 2.764,
    "peak": 0.86,
    "rms": 0.1249
  },
  {
    "id": "crown.point1",
    "speaker": "DISPATCH",
    "text": "Hobbes trusts a strong sovereign to keep order. Locke says rulers must protect rights.",
    "group": "crown",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-crown-point1-f85bff191.mp3",
    "duration": 4.759,
    "peak": 0.86,
    "rms": 0.1293
  },
  {
    "id": "crown.point2",
    "speaker": "DISPATCH",
    "text": "Life, liberty, property. Consent gives government its authority.",
    "group": "crown",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-crown-point2-b0a206211.mp3",
    "duration": 3.963,
    "peak": 0.86,
    "rms": 0.1421
  },
  {
    "id": "molasses.brief",
    "speaker": "NARRATOR",
    "text": "Pick up five cargo barrels and make the northern harbor. Dodge cannon fire. Return your own.",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-molasses-brief-599c9806c.mp3",
    "duration": 6.206,
    "peak": 0.86,
    "rms": 0.1362
  },
  {
    "id": "molasses.after",
    "speaker": "NARRATOR",
    "text": "The Molasses Act taxed foreign molasses. Salutary neglect meant weak enforcement, so smuggling flourished even though it remained illegal.",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-molasses-after-228407c8c.mp3",
    "duration": 9.134,
    "peak": 0.86,
    "rms": 0.1331
  },
  {
    "id": "molasses.line0",
    "speaker": "MATE",
    "text": "French molasses is cheaper. London puts a duty on it.",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.09,
    "lang": "en-gb",
    "file": "voice-molasses-line0-f0b6acd7c.mp3",
    "duration": 3.782,
    "peak": 0.86,
    "rms": 0.1346
  },
  {
    "id": "molasses.line1",
    "speaker": "MATE",
    "text": "Walpole’s men hardly check. They call it salutary neglect.",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.09,
    "lang": "en-gb",
    "file": "voice-molasses-line1-d597cc2b1.mp3",
    "duration": 3.945,
    "peak": 0.7759,
    "rms": 0.15
  },
  {
    "id": "molasses.line2",
    "speaker": "LOOKOUT",
    "text": "Patrol off the bow! Loose enforcement doesn’t make this legal.",
    "group": "molasses",
    "voice": "am_puck",
    "speed": 1.12,
    "lang": "en-us",
    "file": "voice-molasses-line2-cfae81e2e.mp3",
    "duration": 3.298,
    "peak": 0.86,
    "rms": 0.1118
  },
  {
    "id": "pitt.brief",
    "speaker": "NARRATOR",
    "text": "Place defenders. Hold three approaches. Help is coming—but not from the Albany Plan.",
    "group": "pitt",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-pitt-brief-5f953f5b3.mp3",
    "duration": 5.834,
    "peak": 0.8426,
    "rms": 0.15
  },
  {
    "id": "pitt.after",
    "speaker": "NARRATOR",
    "text": "The Albany Plan proposed colonial union but was never implemented. Pitt’s major investment in troops and supplies helped turn the war in Britain’s favor from 1758.",
    "group": "pitt",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-pitt-after-966b578e2.mp3",
    "duration": 12.051,
    "peak": 0.86,
    "rms": 0.1495
  },
  {
    "id": "pitt.line0",
    "speaker": "RUNNER",
    "text": "Albany’s union plan failed. The colonies won’t give up their authority.",
    "group": "pitt",
    "voice": "am_puck",
    "speed": 1.1,
    "lang": "en-us",
    "file": "voice-pitt-line0-0785a4657.mp3",
    "duration": 4.125,
    "peak": 0.86,
    "rms": 0.1169
  },
  {
    "id": "pitt.line1",
    "speaker": "OFFICER",
    "text": "Franklin wanted joint defense under the crown. We’re still on our own.",
    "group": "pitt",
    "voice": "bm_fable",
    "speed": 1.06,
    "lang": "en-gb",
    "file": "voice-pitt-line1-05aaef20d.mp3",
    "duration": 4.377,
    "peak": 0.86,
    "rms": 0.0862
  },
  {
    "id": "pitt.line2",
    "speaker": "RUNNER",
    "text": "Pitt’s funding has arrived! Guns, supplies, reinforcements—use them!",
    "group": "pitt",
    "voice": "am_puck",
    "speed": 1.1,
    "lang": "en-us",
    "file": "voice-pitt-line2-e3799d63a.mp3",
    "duration": 3.863,
    "peak": 0.86,
    "rms": 0.1252
  },
  {
    "id": "quebec.brief",
    "speaker": "NARRATOR",
    "text": "Push through the French positions. Clear each objective and capture the ridge.",
    "group": "quebec",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-quebec-brief-062a8f60c.mp3",
    "duration": 4.921,
    "peak": 0.86,
    "rms": 0.145
  },
  {
    "id": "quebec.after",
    "speaker": "NARRATOR",
    "text": "Quebec fell in 1759 after Wolfe defeated Montcalm. Both commanders were fatally wounded. Montreal fell in 1760; the Treaty of Paris ended the war in 1763.",
    "group": "quebec",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-quebec-after-baf363c78.mp3",
    "duration": 13.799,
    "peak": 0.86,
    "rms": 0.1475
  },
  {
    "id": "quebec.line0",
    "speaker": "OFFICER",
    "text": "Pitt paid for this push. Keep moving. Use the cover.",
    "group": "quebec",
    "voice": "bm_fable",
    "speed": 1.06,
    "lang": "en-gb",
    "file": "voice-quebec-line0-e181e7dd1.mp3",
    "duration": 3.821,
    "peak": 0.86,
    "rms": 0.1059
  },
  {
    "id": "quebec.line1",
    "speaker": "SCOUT",
    "text": "Wolfe’s advancing on the heights. Clear a route through.",
    "group": "quebec",
    "voice": "am_fenrir",
    "speed": 1.08,
    "lang": "en-us",
    "file": "voice-quebec-line1-30e218d26.mp3",
    "duration": 2.826,
    "peak": 0.86,
    "rms": 0.1173
  },
  {
    "id": "quebec.point0",
    "speaker": "DISPATCH",
    "text": "Forward battery secured. Push through!",
    "group": "quebec",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-quebec-point0-b59c19d1e.mp3",
    "duration": 2.405,
    "peak": 0.86,
    "rms": 0.1197
  },
  {
    "id": "quebec.point1",
    "speaker": "DISPATCH",
    "text": "The heights are ours. Wolfe and Montcalm both fell in the battle.",
    "group": "quebec",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-quebec-point1-9df862d9f.mp3",
    "duration": 3.494,
    "peak": 0.86,
    "rms": 0.14
  },
  {
    "id": "quebec.point2",
    "speaker": "DISPATCH",
    "text": "Quebec falls. Montreal follows in 1760. The war ends in 1763.",
    "group": "quebec",
    "voice": "bf_emma",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-quebec-point2-4bee9689c.mp3",
    "duration": 5.546,
    "peak": 0.86,
    "rms": 0.0929
  },
  {
    "id": "debt.brief",
    "speaker": "NARRATOR",
    "text": "Keep Canada, the Ohio frontier, and Florida supplied for sixty seconds. Your treasury is nearly empty.",
    "group": "debt",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-debt-brief-4082ab1c7.mp3",
    "duration": 7.183,
    "peak": 0.86,
    "rms": 0.1284
  },
  {
    "id": "debt.after",
    "speaker": "NARRATOR",
    "text": "Britain’s victory created debt and new defense costs. Taxes, tighter control, and frontier disputes would strain ties with colonists accustomed to autonomy.",
    "group": "debt",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-debt-after-dc88c1f1c.mp3",
    "duration": 10.956,
    "peak": 0.86,
    "rms": 0.1391
  },
  {
    "id": "debt.line0",
    "speaker": "TREASURER",
    "text": "Canada and Florida are ours. So is the bill.",
    "group": "debt",
    "voice": "bm_george",
    "speed": 1,
    "lang": "en-gb",
    "file": "voice-debt-line0-46734365c.mp3",
    "duration": 3.457,
    "peak": 0.86,
    "rms": 0.1364
  },
  {
    "id": "debt.line1",
    "speaker": "COLONIST",
    "text": "We celebrated as British subjects. Now you demand more money?",
    "group": "debt",
    "voice": "af_bella",
    "speed": 1.05,
    "lang": "en-us",
    "file": "voice-debt-line1-5a87b65c5.mp3",
    "duration": 3.593,
    "peak": 0.86,
    "rms": 0.125
  },
  {
    "id": "debt.line2",
    "speaker": "RUNNER",
    "text": "Native nations still defend this land. A treaty doesn’t erase them.",
    "group": "debt",
    "voice": "am_puck",
    "speed": 1.1,
    "lang": "en-us",
    "file": "voice-debt-line2-a8b34e11b.mp3",
    "duration": 3.871,
    "peak": 0.86,
    "rms": 0.1248
  },
  {
    "id": "debt.line3",
    "speaker": "COLONIST",
    "text": "We governed ourselves for years. Why the tighter control now?",
    "group": "debt",
    "voice": "af_bella",
    "speed": 1.05,
    "lang": "en-us",
    "file": "voice-debt-line3-2d5b8eee0.mp3",
    "duration": 3.484,
    "peak": 0.86,
    "rms": 0.1122
  },
  {
    "id": "cargo.full",
    "speaker": "MATE",
    "text": "Hold is full. Make the north harbor!",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.09,
    "lang": "en-gb",
    "file": "voice-cargo-full-8d96f1289.mp3",
    "duration": 2.441,
    "peak": 0.7847,
    "rms": 0.15
  },
  {
    "id": "cargo.first",
    "speaker": "MATE",
    "text": "One barrel aboard. Keep us moving!",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.09,
    "lang": "en-gb",
    "file": "voice-cargo-first-e4dd07616.mp3",
    "duration": 2.48,
    "peak": 0.6745,
    "rms": 0.15
  },
  {
    "id": "cargo.three",
    "speaker": "LOOKOUT",
    "text": "Three aboard! Two more, then we head for the harbor.",
    "group": "molasses",
    "voice": "am_puck",
    "speed": 1.12,
    "lang": "en-us",
    "file": "voice-cargo-three-6cc37332a.mp3",
    "duration": 2.522,
    "peak": 0.86,
    "rms": 0.1229
  },
  {
    "id": "tax",
    "speaker": "COLONIST",
    "text": "More taxes? We never consented to this.",
    "group": "debt",
    "voice": "af_bella",
    "speed": 1.05,
    "lang": "en-us",
    "file": "voice-tax-f1984cf05.mp3",
    "duration": 2.379,
    "peak": 0.86,
    "rms": 0.1238
  },
  {
    "id": "borrow",
    "speaker": "TREASURER",
    "text": "Another loan. Victory keeps getting more expensive.",
    "group": "debt",
    "voice": "bm_george",
    "speed": 1,
    "lang": "en-gb",
    "file": "voice-borrow-65f9d7a75.mp3",
    "duration": 3.34,
    "peak": 0.7558,
    "rms": 0.15
  },
  {
    "id": "health",
    "speaker": "SCOUT",
    "text": "Get behind cover! Catch your breath before you push again.",
    "group": "quebec",
    "voice": "am_fenrir",
    "speed": 1.08,
    "lang": "en-us",
    "file": "voice-health-118c93e82.mp3",
    "duration": 3.121,
    "peak": 0.86,
    "rms": 0.0946
  },
  {
    "id": "captured",
    "speaker": "OFFICER",
    "text": "Position secured. Move to the next flag!",
    "group": "quebec",
    "voice": "bm_fable",
    "speed": 1.06,
    "lang": "en-gb",
    "file": "voice-captured-7b6735b9e.mp3",
    "duration": 3.326,
    "peak": 0.86,
    "rms": 0.1066
  },
  {
    "id": "hull",
    "speaker": "MATE",
    "text": "We’re taking water! Keep moving across their cannon fire!",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.09,
    "lang": "en-gb",
    "file": "voice-hull-746d8dbcd.mp3",
    "duration": 3.492,
    "peak": 0.7619,
    "rms": 0.15
  },
  {
    "id": "spotted",
    "speaker": "NEIGHBOR",
    "text": "They’ve seen you! Break their line of sight!",
    "group": "ashes",
    "voice": "af_heart",
    "speed": 1.08,
    "lang": "en-us",
    "file": "voice-spotted-ce4be8600.mp3",
    "duration": 2.109,
    "peak": 0.86,
    "rms": 0.1482
  },
  {
    "id": "spotted.crown",
    "speaker": "PRINTER",
    "text": "The patrol’s onto you! Get out of sight!",
    "group": "crown",
    "voice": "bm_george",
    "speed": 1.03,
    "lang": "en-gb",
    "file": "voice-spotted-crown-fac55a62e.mp3",
    "duration": 2.697,
    "peak": 0.7815,
    "rms": 0.15
  },
  {
    "id": "home.built",
    "speaker": "NEWCOMER",
    "text": "A home at last. Now we need food for the families.",
    "group": "haven",
    "voice": "af_heart",
    "speed": 1,
    "lang": "en-us",
    "file": "voice-home-built-f570f1c5a.mp3",
    "duration": 3.109,
    "peak": 0.8586,
    "rms": 0.15
  },
  {
    "id": "farm.built",
    "speaker": "PENN",
    "text": "Good. A farm can feed six people. Keep the homes coming.",
    "group": "haven",
    "voice": "bm_fable",
    "speed": 0.97,
    "lang": "en-gb",
    "file": "voice-farm-built-1996568d4.mp3",
    "duration": 4.511,
    "peak": 0.86,
    "rms": 0.1129
  },
  {
    "id": "meeting.built",
    "speaker": "FRIEND",
    "text": "A meetinghouse. We can worship here without an official church ruling us.",
    "group": "haven",
    "voice": "bf_emma",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-meeting-built-782a66917.mp3",
    "duration": 3.901,
    "peak": 0.86,
    "rms": 0.1435
  },
  {
    "id": "fort",
    "speaker": "OFFICER",
    "text": "They’ve reached the fort! Cover all three approaches!",
    "group": "pitt",
    "voice": "bm_fable",
    "speed": 1.06,
    "lang": "en-gb",
    "file": "voice-fort-befcc934b.mp3",
    "duration": 3.486,
    "peak": 0.86,
    "rms": 0.1271
  },
  {
    "id": "treasury",
    "speaker": "TREASURER",
    "text": "The treasury’s nearly empty. Taxes or another loan?",
    "group": "debt",
    "voice": "bm_george",
    "speed": 1,
    "lang": "en-gb",
    "file": "voice-treasury-28776c947.mp3",
    "duration": 3.822,
    "peak": 0.86,
    "rms": 0.1225
  },
  {
    "id": "canada",
    "speaker": "RUNNER",
    "text": "Canada needs supplies. Keep that garrison fed!",
    "group": "debt",
    "voice": "am_puck",
    "speed": 1.1,
    "lang": "en-us",
    "file": "voice-canada-8b1b7ad50.mp3",
    "duration": 2.682,
    "peak": 0.86,
    "rms": 0.1465
  },
  {
    "id": "ohio",
    "speaker": "RUNNER",
    "text": "The Ohio frontier is running short. Send supplies!",
    "group": "debt",
    "voice": "am_puck",
    "speed": 1.1,
    "lang": "en-us",
    "file": "voice-ohio-156bb30b4.mp3",
    "duration": 3.211,
    "peak": 0.86,
    "rms": 0.1249
  },
  {
    "id": "florida",
    "speaker": "RUNNER",
    "text": "Florida’s supplies are almost gone!",
    "group": "debt",
    "voice": "am_puck",
    "speed": 1.1,
    "lang": "en-us",
    "file": "voice-florida-06165fcec.mp3",
    "duration": 1.766,
    "peak": 0.86,
    "rms": 0.1482
  },
  {
    "id": "fail.fps",
    "speaker": "OFFICER",
    "text": "Fall back! Use the cover. We’ll take another run at it.",
    "group": "quebec",
    "voice": "bm_fable",
    "speed": 1.06,
    "lang": "en-gb",
    "file": "voice-fail-fps-0aa14b814.mp3",
    "duration": 3.92,
    "peak": 0.86,
    "rms": 0.0938
  },
  {
    "id": "fail.stealth",
    "speaker": "NEIGHBOR",
    "text": "They found us. Stay low next time. Use a stone to draw the patrol away.",
    "group": "ashes",
    "voice": "af_heart",
    "speed": 1.08,
    "lang": "en-us",
    "file": "voice-fail-stealth-2977eb6ea.mp3",
    "duration": 4.418,
    "peak": 0.86,
    "rms": 0.1423
  },
  {
    "id": "fail.naval",
    "speaker": "MATE",
    "text": "We’ve lost the ship. Next time, keep moving and return fire.",
    "group": "molasses",
    "voice": "bm_george",
    "speed": 1.09,
    "lang": "en-gb",
    "file": "voice-fail-naval-0faecc169.mp3",
    "duration": 3.862,
    "peak": 0.7747,
    "rms": 0.15
  },
  {
    "id": "fail.defense",
    "speaker": "OFFICER",
    "text": "The line has broken. Guard every approach, and use the barrage.",
    "group": "pitt",
    "voice": "bm_fable",
    "speed": 1.06,
    "lang": "en-gb",
    "file": "voice-fail-defense-d026710db.mp3",
    "duration": 4.478,
    "peak": 0.86,
    "rms": 0.1248
  },
  {
    "id": "fail.crisis",
    "speaker": "TREASURER",
    "text": "The supplies ran out. We needed more revenue before the garrison failed.",
    "group": "debt",
    "voice": "bm_george",
    "speed": 1,
    "lang": "en-gb",
    "file": "voice-fail-crisis-f13a16395.mp3",
    "duration": 4.717,
    "peak": 0.86,
    "rms": 0.1467
  },
  {
    "id": "ending",
    "speaker": "NARRATOR",
    "text": "You won the empire. Can you keep it? In seventeen sixty-three, many colonists were proud to be British. Debt, new territory, and tighter control would turn victory into a conflict over who should pay, and who should decide.",
    "group": "ending",
    "voice": "bm_george",
    "speed": 1.01,
    "lang": "en-gb",
    "file": "voice-ending-595a790e3.mp3",
    "duration": 14.148,
    "peak": 0.86,
    "rms": 0.1497
  },
  {
    "id": "test",
    "speaker": "OFFICER",
    "text": "Hold your position. Keep your head down, and listen for my orders.",
    "group": "settings",
    "voice": "bm_fable",
    "speed": 1.06,
    "lang": "en-gb",
    "file": "voice-test-9d51d50d8.mp3",
    "duration": 4.399,
    "peak": 0.86,
    "rms": 0.1076
  }
];
